part of 'libxl_ext.dart';


  int _xlCreateBook() native "_xlCreateBook";
  int _xlCreateXMLBook() native "_xlCreateXMLBook";
  int _xlBookLoad(int handle, String filename) native "_xlBookLoad";
  int _xlBookSave(int handle, String filename) native "_xlBookSave";
  int _xlBookLoadUsingTempFile(int handle, String filename, String tempFile) native "_xlBookLoadUsingTempFile";
  int _xlBookSaveUsingTempFile(int handle, String filename, int useTempFile) native "_xlBookSaveUsingTempFile";
  int _xlBookLoadPartially(int handle, String filename, int sheetIndex, int firstRow, int lastRow) native "_xlBookLoadPartially";
  int _xlBookLoadPartiallyUsingTempFile(int handle, String filename, int sheetIndex, int firstRow, int lastRow, String tempFile) native "_xlBookLoadPartiallyUsingTempFile";
  int _xlBookLoadWithoutEmptyCells(int handle, String filename) native "_xlBookLoadWithoutEmptyCells";
  int _xlBookAddSheet(int handle, String name, int initSheet) native "_xlBookAddSheet";
  int _xlBookInsertSheet(int handle, int index, String name, int initSheet) native "_xlBookInsertSheet";
  int _xlBookGetSheet(int handle, int index) native "_xlBookGetSheet";
  int _xlBookSheetType(int handle, int index) native "_xlBookSheetType";
  int _xlBookMoveSheet(int handle, int srcIndex, int dstIndex) native "_xlBookMoveSheet";
  int _xlBookDelSheet(int handle, int index) native "_xlBookDelSheet";
  int _xlBookSheetCount(int handle) native "_xlBookSheetCount";
  int _xlBookAddFormat(int handle, int initFormat) native "_xlBookAddFormat";
  int _xlBookAddFont(int handle, int initFont) native "_xlBookAddFont";
  int _xlBookAddCustomNumFormat(int handle, String customNumFormat) native "_xlBookAddCustomNumFormat";
  String _xlBookCustomNumFormat(int handle, int fmt) native "_xlBookCustomNumFormat";
  int _xlBookFormat(int handle, int index) native "_xlBookFormat";
  int _xlBookFormatSize(int handle) native "_xlBookFormatSize";
  int _xlBookFont(int handle, int index) native "_xlBookFont";
  int _xlBookFontSize(int handle) native "_xlBookFontSize";
  num _xlBookDatePack(int handle, int year, int month, int day, int hour, int min, int sec, int msec) native "_xlBookDatePack";
  int _xlBookColorPack(int handle, int red, int green, int blue) native "_xlBookColorPack";
  int _xlBookActiveSheet(int handle) native "_xlBookActiveSheet";
  void _xlBookSetActiveSheet(int handle, int index) native "_xlBookSetActiveSheet";
  int _xlBookPictureSize(int handle) native "_xlBookPictureSize";
  int _xlBookAddPicture(int handle, String filename) native "_xlBookAddPicture";
  int _xlBookAddPictureAsLink(int handle, String filename, int insert) native "_xlBookAddPictureAsLink";
  void _xlBookSetDefaultFont(int handle, String fontName, int fontSize) native "_xlBookSetDefaultFont";
  int _xlBookRefR1C1(int handle) native "_xlBookRefR1C1";
  void _xlBookSetRefR1C1(int handle, int refR1C1) native "_xlBookSetRefR1C1";
  void _xlBookSetKey(int handle, String name, String key) native "_xlBookSetKey";
  int _xlBookRgbMode(int handle) native "_xlBookRgbMode";
  void _xlBookSetRgbMode(int handle, int rgbMode) native "_xlBookSetRgbMode";
  int _xlBookVersion(int handle) native "_xlBookVersion";
  int _xlBookBiffVersion(int handle) native "_xlBookBiffVersion";
  int _xlBookIsDate1904(int handle) native "_xlBookIsDate1904";
  void _xlBookSetDate1904(int handle, int date1904) native "_xlBookSetDate1904";
  int _xlBookIsTemplate(int handle) native "_xlBookIsTemplate";
  void _xlBookSetTemplate(int handle, int tmpl) native "_xlBookSetTemplate";
  int _xlBookSetLocale(int handle, String locale) native "_xlBookSetLocale";
  String _xlBookErrorMessage(int handle) native "_xlBookErrorMessage";
  void _xlBookRelease(int handle) native "_xlBookRelease";
