part of 'libxl_ext.dart';


  int _xlFormatFont(int handle) native "_xlFormatFont";
  int _xlFormatSetFont(int handle, int fontHandle) native "_xlFormatSetFont";
  int _xlFormatNumFormat(int handle) native "_xlFormatNumFormat";
  void _xlFormatSetNumFormat(int handle, int numFormat) native "_xlFormatSetNumFormat";
  int _xlFormatAlignH(int handle) native "_xlFormatAlignH";
  void _xlFormatSetAlignH(int handle, int align) native "_xlFormatSetAlignH";
  int _xlFormatAlignV(int handle) native "_xlFormatAlignV";
  void _xlFormatSetAlignV(int handle, int align) native "_xlFormatSetAlignV";
  int _xlFormatWrap(int handle) native "_xlFormatWrap";
  void _xlFormatSetWrap(int handle, int wrap) native "_xlFormatSetWrap";
  int _xlFormatRotation(int handle) native "_xlFormatRotation";
  int _xlFormatSetRotation(int handle, int rotation) native "_xlFormatSetRotation";
  int _xlFormatIndent(int handle) native "_xlFormatIndent";
  void _xlFormatSetIndent(int handle, int indent) native "_xlFormatSetIndent";
  int _xlFormatShrinkToFit(int handle) native "_xlFormatShrinkToFit";
  void _xlFormatSetShrinkToFit(int handle, int shrinkToFit) native "_xlFormatSetShrinkToFit";
  void _xlFormatSetBorder(int handle, int style) native "_xlFormatSetBorder";
  void _xlFormatSetBorderColor(int handle, int color) native "_xlFormatSetBorderColor";
  int _xlFormatBorderLeft(int handle) native "_xlFormatBorderLeft";
  void _xlFormatSetBorderLeft(int handle, int style) native "_xlFormatSetBorderLeft";
  int _xlFormatBorderRight(int handle) native "_xlFormatBorderRight";
  void _xlFormatSetBorderRight(int handle, int style) native "_xlFormatSetBorderRight";
  int _xlFormatBorderTop(int handle) native "_xlFormatBorderTop";
  void _xlFormatSetBorderTop(int handle, int style) native "_xlFormatSetBorderTop";
  int _xlFormatBorderBottom(int handle) native "_xlFormatBorderBottom";
  void _xlFormatSetBorderBottom(int handle, int style) native "_xlFormatSetBorderBottom";
  int _xlFormatBorderLeftColor(int handle) native "_xlFormatBorderLeftColor";
  void _xlFormatSetBorderLeftColor(int handle, int color) native "_xlFormatSetBorderLeftColor";
  int _xlFormatBorderRightColor(int handle) native "_xlFormatBorderRightColor";
  void _xlFormatSetBorderRightColor(int handle, int color) native "_xlFormatSetBorderRightColor";
  int _xlFormatBorderTopColor(int handle) native "_xlFormatBorderTopColor";
  void _xlFormatSetBorderTopColor(int handle, int color) native "_xlFormatSetBorderTopColor";
  int _xlFormatBorderBottomColor(int handle) native "_xlFormatBorderBottomColor";
  void _xlFormatSetBorderBottomColor(int handle, int color) native "_xlFormatSetBorderBottomColor";
  int _xlFormatBorderDiagonal(int handle) native "_xlFormatBorderDiagonal";
  void _xlFormatSetBorderDiagonal(int handle, int border) native "_xlFormatSetBorderDiagonal";
  int _xlFormatBorderDiagonalStyle(int handle) native "_xlFormatBorderDiagonalStyle";
  void _xlFormatSetBorderDiagonalStyle(int handle, int style) native "_xlFormatSetBorderDiagonalStyle";
  int _xlFormatBorderDiagonalColor(int handle) native "_xlFormatBorderDiagonalColor";
  void _xlFormatSetBorderDiagonalColor(int handle, int color) native "_xlFormatSetBorderDiagonalColor";
  int _xlFormatFillPattern(int handle) native "_xlFormatFillPattern";
  void _xlFormatSetFillPattern(int handle, int pattern) native "_xlFormatSetFillPattern";
  int _xlFormatPatternForegroundColor(int handle) native "_xlFormatPatternForegroundColor";
  void _xlFormatSetPatternForegroundColor(int handle, int color) native "_xlFormatSetPatternForegroundColor";
  int _xlFormatPatternBackgroundColor(int handle) native "_xlFormatPatternBackgroundColor";
  void _xlFormatSetPatternBackgroundColor(int handle, int color) native "_xlFormatSetPatternBackgroundColor";
  int _xlFormatLocked(int handle) native "_xlFormatLocked";
  void _xlFormatSetLocked(int handle, int locked) native "_xlFormatSetLocked";
  int _xlFormatHidden(int handle) native "_xlFormatHidden";
  void _xlFormatSetHidden(int handle, int hidden) native "_xlFormatSetHidden";
