part of 'libxl_ext.dart';


  int _xlSheetCellType(int handle, int row, int col) native "_xlSheetCellType";
  int _xlSheetIsFormula(int handle, int row, int col) native "_xlSheetIsFormula";
  int _xlSheetCellFormat(int handle, int row, int col) native "_xlSheetCellFormat";
  void _xlSheetSetCellFormat(int handle, int row, int col, int format) native "_xlSheetSetCellFormat";
  int _xlSheetWriteStr(int handle, int row, int col, String value, int format) native "_xlSheetWriteStr";
  int _xlSheetWriteNum(int handle, int row, int col, num value, int format) native "_xlSheetWriteNum";
  int _xlSheetWriteBool(int handle, int row, int col, int value, int format) native "_xlSheetWriteBool";
  int _xlSheetWriteBlank(int handle, int row, int col, int format) native "_xlSheetWriteBlank";
  int _xlSheetWriteFormula(int handle, int row, int col, String value, int format) native "_xlSheetWriteFormula";
  int _xlSheetWriteFormulaNum(int handle, int row, int col, String expr, num value, int format) native "_xlSheetWriteFormulaNum";
  int _xlSheetWriteFormulaStr(int handle, int row, int col, String expr, String value, int format) native "_xlSheetWriteFormulaStr";
  int _xlSheetWriteFormulaBool(int handle, int row, int col, String expr, int value, int format) native "_xlSheetWriteFormulaBool";
  String _xlSheetReadComment(int handle, int row, int col) native "_xlSheetReadComment";
  void _xlSheetWriteComment(int handle, int row, int col, String value, String author, int width, int height) native "_xlSheetWriteComment";
  void _xlSheetRemoveComment(int handle, int row, int col) native "_xlSheetRemoveComment";
  int _xlSheetIsDate(int handle, int row, int col) native "_xlSheetIsDate";
  int _xlSheetReadError(int handle, int row, int col) native "_xlSheetReadError";
  void _xlSheetWriteError(int handle, int row, int col, int error, int format) native "_xlSheetWriteError";
  num _xlSheetColWidth(int handle, int col) native "_xlSheetColWidth";
  num _xlSheetRowHeight(int handle, int row) native "_xlSheetRowHeight";
  int _xlSheetSetCol(int handle, int colFirst, int colLast, num width, int format, int hidden) native "_xlSheetSetCol";
  int _xlSheetSetRow(int handle, int row, num height, int format, int hidden) native "_xlSheetSetRow";
  int _xlSheetRowHidden(int handle, int row) native "_xlSheetRowHidden";
  int _xlSheetSetRowHidden(int handle, int row, int hidden) native "_xlSheetSetRowHidden";
  int _xlSheetColHidden(int handle, int col) native "_xlSheetColHidden";
  int _xlSheetSetColHidden(int handle, int col, int hidden) native "_xlSheetSetColHidden";
  int _xlSheetSetMerge(int handle, int rowFirst, int rowLast, int colFirst, int colLast) native "_xlSheetSetMerge";
  int _xlSheetDelMerge(int handle, int row, int col) native "_xlSheetDelMerge";
  int _xlSheetMergeSize(int handle) native "_xlSheetMergeSize";
  int _xlSheetDelMergeByIndex(int handle, int index) native "_xlSheetDelMergeByIndex";
  int _xlSheetPictureSize(int handle) native "_xlSheetPictureSize";
  void _xlSheetSetPicture(int handle, int row, int col, int pictureId, num scale, int offset_x, int offset_y, int pos) native "_xlSheetSetPicture";
  void _xlSheetSetPicture2(int handle, int row, int col, int pictureId, int width, int height, int offset_x, int offset_y, int pos) native "_xlSheetSetPicture2";
  int _xlSheetGetHorPageBreak(int handle, int index) native "_xlSheetGetHorPageBreak";
  int _xlSheetGetHorPageBreakSize(int handle) native "_xlSheetGetHorPageBreakSize";
  int _xlSheetGetVerPageBreak(int handle, int index) native "_xlSheetGetVerPageBreak";
  int _xlSheetGetVerPageBreakSize(int handle) native "_xlSheetGetVerPageBreakSize";
  int _xlSheetSetHorPageBreak(int handle, int row, int pageBreak) native "_xlSheetSetHorPageBreak";
  int _xlSheetSetVerPageBreak(int handle, int col, int pageBreak) native "_xlSheetSetVerPageBreak";
  void _xlSheetSplit(int handle, int row, int col) native "_xlSheetSplit";
  int _xlSheetGroupRows(int handle, int rowFirst, int rowLast, int collapsed) native "_xlSheetGroupRows";
  int _xlSheetGroupCols(int handle, int colFirst, int colLast, int collapsed) native "_xlSheetGroupCols";
  int _xlSheetGroupSummaryBelow(int handle) native "_xlSheetGroupSummaryBelow";
  void _xlSheetSetGroupSummaryBelow(int handle, int below) native "_xlSheetSetGroupSummaryBelow";
  int _xlSheetGroupSummaryRight(int handle) native "_xlSheetGroupSummaryRight";
  void _xlSheetSetGroupSummaryRight(int handle, int right) native "_xlSheetSetGroupSummaryRight";
  void _xlSheetClear(int handle, int rowFirst, int rowLast, int colFirst, int colLast) native "_xlSheetClear";
  int _xlSheetInsertCol(int handle, int colFirst, int colLast) native "_xlSheetInsertCol";
  int _xlSheetInsertRow(int handle, int rowFirst, int rowLast) native "_xlSheetInsertRow";
  int _xlSheetRemoveCol(int handle, int colFirst, int colLast) native "_xlSheetRemoveCol";
  int _xlSheetRemoveRow(int handle, int rowFirst, int rowLast) native "_xlSheetRemoveRow";
  int _xlSheetCopyCell(int handle, int rowSrc, int colSrc, int rowDst, int colDst) native "_xlSheetCopyCell";
  int _xlSheetFirstRow(int handle) native "_xlSheetFirstRow";
  int _xlSheetLastRow(int handle) native "_xlSheetLastRow";
  int _xlSheetFirstCol(int handle) native "_xlSheetFirstCol";
  int _xlSheetLastCol(int handle) native "_xlSheetLastCol";
  int _xlSheetDisplayGridlines(int handle) native "_xlSheetDisplayGridlines";
  void _xlSheetSetDisplayGridlines(int handle, int show) native "_xlSheetSetDisplayGridlines";
  int _xlSheetPrintGridlines(int handle) native "_xlSheetPrintGridlines";
  void _xlSheetSetPrintGridlines(int handle, int print) native "_xlSheetSetPrintGridlines";
  int _xlSheetZoom(int handle) native "_xlSheetZoom";
  void _xlSheetSetZoom(int handle, int zoom) native "_xlSheetSetZoom";
  int _xlSheetPrintZoom(int handle) native "_xlSheetPrintZoom";
  void _xlSheetSetPrintZoom(int handle, int zoom) native "_xlSheetSetPrintZoom";
  void _xlSheetSetPrintFit(int handle, int wPages, int hPages) native "_xlSheetSetPrintFit";
  int _xlSheetLandscape(int handle) native "_xlSheetLandscape";
  void _xlSheetSetLandscape(int handle, int landscape) native "_xlSheetSetLandscape";
  int _xlSheetPaper(int handle) native "_xlSheetPaper";
  void _xlSheetSetPaper(int handle, int paper) native "_xlSheetSetPaper";
  String _xlSheetHeader(int handle) native "_xlSheetHeader";
  int _xlSheetSetHeader(int handle, String header, num margin) native "_xlSheetSetHeader";
  num _xlSheetHeaderMargin(int handle) native "_xlSheetHeaderMargin";
  String _xlSheetFooter(int handle) native "_xlSheetFooter";
  int _xlSheetSetFooter(int handle, String footer, num margin) native "_xlSheetSetFooter";
  num _xlSheetFooterMargin(int handle) native "_xlSheetFooterMargin";
  int _xlSheetHCenter(int handle) native "_xlSheetHCenter";
  void _xlSheetSetHCenter(int handle, int hCenter) native "_xlSheetSetHCenter";
  int _xlSheetVCenter(int handle) native "_xlSheetVCenter";
  void _xlSheetSetVCenter(int handle, int vCenter) native "_xlSheetSetVCenter";
  num _xlSheetMarginLeft(int handle) native "_xlSheetMarginLeft";
  void _xlSheetSetMarginLeft(int handle, num margin) native "_xlSheetSetMarginLeft";
  num _xlSheetMarginRight(int handle) native "_xlSheetMarginRight";
  void _xlSheetSetMarginRight(int handle, num margin) native "_xlSheetSetMarginRight";
  num _xlSheetMarginTop(int handle) native "_xlSheetMarginTop";
  void _xlSheetSetMarginTop(int handle, num margin) native "_xlSheetSetMarginTop";
  num _xlSheetMarginBottom(int handle) native "_xlSheetMarginBottom";
  void _xlSheetSetMarginBottom(int handle, num margin) native "_xlSheetSetMarginBottom";
  int _xlSheetPrintRowCol(int handle) native "_xlSheetPrintRowCol";
  void _xlSheetSetPrintRowCol(int handle, int print) native "_xlSheetSetPrintRowCol";
  void _xlSheetSetPrintRepeatRows(int handle, int rowFirst, int rowLast) native "_xlSheetSetPrintRepeatRows";
  void _xlSheetSetPrintRepeatCols(int handle, int colFirst, int colLast) native "_xlSheetSetPrintRepeatCols";
  void _xlSheetSetPrintArea(int handle, int rowFirst, int rowLast, int colFirst, int colLast) native "_xlSheetSetPrintArea";
  void _xlSheetClearPrintRepeats(int handle) native "_xlSheetClearPrintRepeats";
  void _xlSheetClearPrintArea(int handle) native "_xlSheetClearPrintArea";
  int _xlSheetSetNamedRange(int handle, String name, int rowFirst, int rowLast, int colFirst, int colLast, int scopeId) native "_xlSheetSetNamedRange";
  int _xlSheetDelNamedRange(int handle, String name, int scopeId) native "_xlSheetDelNamedRange";
  int _xlSheetNamedRangeSize(int handle) native "_xlSheetNamedRangeSize";
  int _xlSheetTableSize(int handle) native "_xlSheetTableSize";
  int _xlSheetHyperlinkSize(int handle) native "_xlSheetHyperlinkSize";
  int _xlSheetDelHyperlink(int handle, int index) native "_xlSheetDelHyperlink";
  void _xlSheetAddHyperlink(int handle, String hyperlink, int rowFirst, int rowLast, int colFirst, int colLast) native "_xlSheetAddHyperlink";
  void _xlSheetApplyFilter(int handle) native "_xlSheetApplyFilter";
  void _xlSheetRemoveFilter(int handle) native "_xlSheetRemoveFilter";
  String _xlSheetName(int handle) native "_xlSheetName";
  void _xlSheetSetName(int handle, String name) native "_xlSheetSetName";
  int _xlSheetProtect(int handle) native "_xlSheetProtect";
  void _xlSheetSetProtect(int handle, int protect) native "_xlSheetSetProtect";
  void _xlSheetSetProtectEx(int handle, int protect, String password, int enhancedProtection) native "_xlSheetSetProtectEx";
  int _xlSheetHidden(int handle) native "_xlSheetHidden";
  int _xlSheetSetHidden(int handle, int hidden) native "_xlSheetSetHidden";
  void _xlSheetSetTopLeftView(int handle, int row, int col) native "_xlSheetSetTopLeftView";
  int _xlSheetRightToLeft(int handle) native "_xlSheetRightToLeft";
  void _xlSheetSetRightToLeft(int handle, int rightToLeft) native "_xlSheetSetRightToLeft";
  void _xlSheetSetAutoFitArea(int handle, int rowFirst, int colFirst, int rowLast, int colLast) native "_xlSheetSetAutoFitArea";
  String _xlSheetRowColToAddr(int handle, int row, int col, int rowRelative, int colRelative) native "_xlSheetRowColToAddr";
  void _xlSheetSetTabColor(int handle, int color) native "_xlSheetSetTabColor";
  void _xlSheetSetTabRgbColor(int handle, int red, int green, int blue) native "_xlSheetSetTabRgbColor";
  int _xlSheetAddIgnoredError(int handle, int rowFirst, int colFirst, int rowLast, int colLast, int iError) native "_xlSheetAddIgnoredError";
  void _xlSheetAddDataValidation(int handle, int type, int op, int rowFirst, int rowLast, int colFirst, int colLast, String value1, String value2) native "_xlSheetAddDataValidation";
  void _xlSheetAddDataValidationDouble(int handle, int type, int op, int rowFirst, int rowLast, int colFirst, int colLast, num value1, num value2) native "_xlSheetAddDataValidationDouble";
  void _xlSheetRemoveDataValidations(int handle) native "_xlSheetRemoveDataValidations";
